### ISSUE TITLE
Multiplication of two polynomials 

### ISSUE THREAD

**Issue by dpsanders** [tkoolen/StaticUnivariatePolynomials.jl#2]
Do you have an idea how to implement multiplication of two polynomials in an efficient way?

**Comment by tkoolen** [comment]
In terms of computational complexity as a function of polynomial degree, going through the FFT (Schönhage–Strassen algorithm) is a good way. But for low-order polynomials it's probably (much?) slower compared to a naive O(n^2) algorithm, especially if everything is unrolled and if we can get the compiler to eliminate common subexpressions. So I think the naive thing is the first thing to try.

**Comment by dpsanders** [comment]
Yes I was certainly thinking about the naive algorithm, but I'm trying to get it to not allocate (and preferably unroll) and am not succeeding.
